---
- name: daemon reload
  service:
    name: rabbitmq-server
    daemon_reload: true

- name: restart rabbitmq
  service:
    name: rabbitmq-server
    state: restarted

- name: start rabbitmq app
  command: rabbitmqctl start_app

- name: restart newrelic-infra
  service:
    name: newrelic-infra
    state: restarted
